#!/bin/bash

set -x
set -e

jarball1=CanaryMod-1.7.10-1.1.3.jar
if [ ! -f $jarball1 ] ; then
  wget -c http://canarymod.net/download/file/fid/283 -O $jarball1
fi

jarball2=scriptcraft.jar
if [ ! -f $jarball2 ] ; then
  wget -c http://scriptcraftjs.org/download/latest/scriptcraft-3.1.0/$jarball2
fi

target=$1

mkdir -p $target
cd $target
java -jar ../$jarball1


ln -s ../../$jarball2 plugins

sed -i 's/false/true/' eula.txt
sed -i '/^player-idle-timeout=/ s/=.*$/=120/'   config/server.cfg
sed -i '/^server-locale=/       s/=.*$/=fr_FR/' config/server.cfg
sed -i '/^motd=/       s/=.*$/=Gnancraft/' config/server.cfg
mkdir -p config/worlds/default
cp ../world.cfg config/worlds/default/default_NORMAL.cfg
sed -i '/^world-type=/          s/=.*$/=FLAT/'   config/worlds/default/default_NORMAL.cfg
sed -i '/^generate-structures=/ s/=.*$/=false/'  config/worlds/default/default_NORMAL.cfg
sed -i '/^spawn-.*=/            s/=.*$/=false/'  config/worlds/default/default_NORMAL.cfg

java -jar ../$jarball1
