#!/bin/bash
set -x
set -e

RSYNC_OPT=" --update "
[ -n "${INIT_WORLD:-}" ] && RSYNC_OPT=" --delete "

rsync -a $RSYNC_OPT /opt/minecraft/ /minecraft/
cd /minecraft
[ -n "${OPS:-}" ]         && echo "$OPS" > /minecraft/ops.txt
[ -n "${ONLINE_MODE:-}" ] && sed -i -e "s/^online-mode=.*/online-mode=$ONLINE_MODE/g" /minecraft/server.properties

/etc/init.d/ssh start
echo "jsp classroom on" | /usr/bin/java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xmx8192M -jar spigot-${MINECRAFT_VERSION}.jar
